var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  o             ",
   "                                                                                ",
   "                                                                                ",
   "                                                   x!x   x!x     xxx            ",
   "                                    o o            xxx   xxx                    ",
   "                                             xx                                 ",
   "                                   xxxxx                                        ",
   "  xx                                      o o                     o             ",
   "  x!                             o                      o                       ",
   "  x!                                     x = x                    x             ",
   "  x!                                     xxxxx                   x x         o  ",
   "  x!  @                         x!x                             x   x           ",
   "  xxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxx     xxxxxxxxxx ",
   "             xxxx                                    x     x                    ",
   "                                                     x!!!!!x                    ",
   "                                                     x!!!!!x                    ",
   "                                                     xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                               xxxxxxx                                                            ",
   "                                                     x                                                            ",
   "                                                     x                                                            ",
   "                                       o             x                                                            ",
   "                                               x    =x                                                            ",
   "                                            xxxx xxxxx                                                            ",
   "                                       xx      x     x                                                            ",
   "                                       !x      x     x                                                            ",
   "                                       !xxx    x  o  x                                                            ",
   "                                       !x      x=    x                                                            ",
   "                              xxx   xxxxx    xxxxxxx x                                                            ",
   "                                               x     x                                                            ",
   "           >           xxx                x    x     x     xxx       xxx                                          ",
   "     @                            o            x  o  x      |                                                     ",
   "    xxx   xxx    xxx                          xx    =x                                                            ",
   "                                xxxxx    xxxxxxx xxxxx                            x                               ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                              o   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      |           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx   xxx       xxx   xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xx                                  xxxxxxxxxxxxxxxxxxxxx                                                  x",
   "  x!                                  x!!!!!!!!!!!!!!!!!!!x                                                  x",
   "  x!         xxx           xxx        xvvvvvvvvvvvvvvvvvvvx                                                  x",
   "  x!         |               |                                                                               x",
   "  x!                 o                                                                                       x",
   "  x!                                                                                                         x",
   "  x!          o     xxx     o                                                                                x",
   "  x!           |           |                                                                                 x",
   "  x!         xxx     >     xxx                                         o       o       o                     x",
   "  x!                                      o     o     o            x=       =        =      =x          o    x",
   "  x!     @          xxx                                            xxxxxxxxxxxxxxxxxxxxxxxxxxx               x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "             xx      xx     xxxxxxxx     xx       xx      x         x    o    xx     x           ",
   "              xx    xx      xx    xx     xx       xx      x         x         x x    x           ",
   "                xxxx        xx    xx     xx       xx      x         x    x    x  x   x           ",
   "                 xx         xx    xx     xx       xx       x   x   x     x    x   x  x           ",
   "                 xx         xx    xx     xx       xx        x x x x      x    x    x x           ",
   "                 xx         xxxxxxxx     xxxxxxxxxxx         x   x       x    x     xx           ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "        @                                                                                         ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
